export const getContent = (selectedPost) => [
    { type: "text", value: selectedPost.date, additionalClass: "text-purpleText text-[14px]" },
    { type: "title", value: selectedPost.title },
    { type: "image", src: selectedPost.img, alt: selectedPost.title },
    { type: "text", value: selectedPost.description },
    { type: "text", value: selectedPost.descriptionTwo, additionalClass: "mt-3" },
    { type: "boldText", value: selectedPost.boldText, additionalClass: "mt-3 w-[70%]" },
    { type: "image", src: selectedPost.img_21 },
    { type: "text", value: selectedPost.descriptionFour },
    { type: "text", value: selectedPost.descriptionFive },
    { type: "text", value: selectedPost.descriptionSix },
    { type: "text", value: selectedPost.descriptionSeven },
    { type: "boldText", value: selectedPost.Heading_1 },
    { type: "text", value: selectedPost.descriptionEight },
    { type: "inlineText", heading: selectedPost.Heading_2, description: selectedPost.descriptionNine },
    { type: "inlineText", heading: selectedPost.Heading_3, description: selectedPost.descriptionTen },
    { type: "image", src: selectedPost.img_22 },
    { type: "text", value: selectedPost.desc_1, additionalClass: "text-center mx-auto w-[65%]" },
    { type: "subtitle", value: selectedPost.Heading_4 },
    { type: "boldText", value: selectedPost.Example_1 },
    { type: "text", value: selectedPost.descerptionEleven },
    { type: "image", src: selectedPost.img_23 },
    { type: "text", value: selectedPost.desc_2, additionalClass: "text-center mx-auto w-[70%]" },
    { type: "boldText", value: selectedPost.Example_2 },
    { type: "text", value: selectedPost.descerptionTweleve },
    { type: "image", src: selectedPost.img_24 },
    { type: "text", value: selectedPost.desc_3, additionalClass: "text-center mx-auto w-[70%]" },
    { type: "boldText", value: selectedPost.Example_3 },
    { type: "text", value: selectedPost.descerptionThirteen },
    { type: "image", src: selectedPost.img_25 },
    { type: "text", value: selectedPost.desc_4, additionalClass: "text-center mx-auto w-[70%]" },
    { type: "boldText", value: selectedPost.Example_4 },
    { type: "text", value: selectedPost.descerptionFourteen },
    { type: "image", src: selectedPost.img_26 },
    { type: "text", value: selectedPost.desc_5, additionalClass: "text-center mx-auto w-[70%]" },
    { type: "boldText", value: selectedPost.Benefits },
    { type: "text", value: selectedPost.para },
    { type: "list", items: selectedPost.ul.flatMap(item => [item.li, item.li_2, item.li_3]) },
    { type: "image", src: selectedPost.img_27 }, 
    { type: "text", value: selectedPost.desc_6, additionalClass: "text-center mx-auto w-[70%]" },
    { type: "text", value: selectedPost.evenMore },
    { type: "boldText", value: selectedPost.Chossing },
    { type: "text", value: selectedPost.descOfChoosing },
    { type: "text", value: `${selectedPost.Choose}: ${selectedPost.descOfChoose}` },
    { type: "text", value: `${selectedPost.SpendTime}: ${selectedPost.descOfSpendTime}` },
    { type: "image", src: selectedPost.img_28 },
    { type: "text", value: selectedPost.desc_7, additionalClass: "text-center mx-auto w-[65%]" },
    { type: "text", value: `${selectedPost.Always}: ${selectedPost.descOfAlways}` },
    { type: "image", src: selectedPost.img_29 },
    { type: "text", value: selectedPost.desc_8, additionalClass: "text-center mx-auto w-[65%]" },
    { type: "text", value: `${selectedPost.Consider}: ${selectedPost.descOfConsider}` },
    { type: "boldText", value: selectedPost.Conclusion},
    { type: "text", value: selectedPost.descOfConclusio },
];
